Repository GlueOps/terraform-module-cloud-aws-kubernetes-cluster, pull requests merged in 2024-10, with the labels that each got.

#147 Fix adding kubernetes version to node pool definition otherwise it'll always use the same version as the cluster
  README.md
  docs/.header.md
  node_pool.tf
  tests/main.tf
  variables.tf
Labels: documentation, enhancement, Review effort [1-5]: 2

#160 chore(deps): update actions/checkout digest to eef6144
  .github/workflows/aws-cloud-regression-suite.yml
  .github/workflows/docs.yml
Labels: Review effort [1-5]: 1, patch, include-in-release-notes, auto-update

#163 feat: updates
  README.md
  docs/.header.md
  tests/main.tf
Labels: enhancement, patch, include-in-release-notes, minor, Review effort [1-5]: 2

#164 chore(deps): update dependency glueops/codespaces to v0.59.0
  .github/workflows/aws-cloud-regression-suite.yml
Labels: Review effort [1-5]: 1, patch, include-in-release-notes, auto-update, dependencies

#166 feat: allowing manual runs of regression on demand
  .github/workflows/aws-cloud-regression-suite.yml
Labels: enhancement, Review effort [1-5]: 1, include-in-release-notes, minor, configuration changes

#170 debug: adding empty line to debug why an action isn't running
  README.md
  docs/.header.md
Labels: documentation, Review effort [1-5]: 1

#174 fix: aws-cloud-regression-suite.yml
  .github/workflows/aws-cloud-regression-suite.yml
Labels: Review effort [1-5]: 1, configuration changes

#171 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, configuration changes, sync

#176 Feat/update eks ami
  README.md
  docs/.header.md
  tests/main.tf
  variables.tf
Labels: documentation, enhancement, include-in-release-notes, minor, Review effort [1-5]: 2

#181 feat: update EKS and addon versions so that we can go from 1.28 -> 1.29 upgrade
  README.md
  docs/.header.md
  tests/main.tf
  variables.tf
Labels: enhancement, include-in-release-notes, minor, Review effort [1-5]: 2
